# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator_identifier', models.CharField(blank=True, max_length=15)),
                ('merchant_identifier', models.CharField(max_length=15)),
                ('merchant_order_ref', models.CharField(db_index=True, max_length=250)),
                ('t3m_id', models.CharField(db_index=True, max_length=128)),
                ('score', models.IntegerField()),
                ('recommendation', models.IntegerField()),
                ('message_digest', models.CharField(blank=True, max_length=128)),
                ('raw_response', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=128)),
                ('method', models.CharField(max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='GBP', max_length=12)),
                ('merchant_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('datacash_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('request_xml', models.TextField()),
                ('response_xml', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
